r2_sim_params:
    # list of initial joint positions
    # omitted joints default to 0.0
    initial_position: # start the robot in this position
        radians: false
        r2:
            waist/joint0: 0 # setting joint0 to nonzero doesn't work (inexplicably)
            neck:
                joint0: -5.0
                joint1: 0.0
                joint2: 0.0
            left_arm:
                joint0: 50.0
                joint1: -80.0
                joint2: -105.0
                joint3: -140.0
                joint4: 80.0
                wrist:
                    pitch: 0.0
                    yaw: 0.0
            right_arm:
                joint0: -50.0
                joint1: -80.0
                joint2: 105.0
                joint3: -140.0
                joint4: -80.0
                wrist:
                    pitch: 0.0
                    yaw: 0.0
                        
    # PID values are [kp, ki, kd, imax, imin, command_max, command_min]
    # Only the first 3 are required, the others default to 0.0 meaning they are unused
    # position_pid and velocity_pid are available and should be set for position or velocity control, respectively
    position_pid: 
        r2:
            waist:
                joint0:
                    [800.0, 0, 150]
                    
            neck:
                joint0:
                    [10.0, 0, .9]
                joint1:
                    [10.0, 0, .9]
                joint2:
                    [10.0, 0, .9]
                    
            left_arm:
                joint0:
                    [400.0, 0, 50]
                joint1:
                    [300.0, 0, 40]
                joint2:
                    [100.0, 0, 10]
                joint3:
                    [70.0, 0, 7]
                joint4:
                    [40.0, 0, 2]
                joint5:
                    [10.0, 0, .5]
                joint6:
                    [3.0, 0, .3]
                hand:
                    thumb:
                        joint0:
                            [6, 0.0, 0.3]
                        joint1:
                            [3, 0.0, 0.4]
                        joint2:
                            [.6, 0.0, 0.1]
                        joint3:
                            [.25, 0.0, 0.035]
                    index:
                        joint0:
                            [6, 0.0, 0.3]
                        joint1:
                            [3, 0.0, 0.4]
                        joint2:
                            [.6, 0.0, 0.1]
                        joint3:
                            [.25, 0.0, 0.035]
                    middle:
                        joint0:
                            [6, 0.0, 0.3]
                        joint1:
                            [3, 0.0, 0.4]
                        joint2:
                            [.6, 0.0, 0.1]
                        joint3:
                            [.25, 0.0, 0.035]
                    ring:
                        joint0:
                            [3, 0.0, 0.4]
                        joint1:
                            [.6, 0.0, 0.1]
                        joint2:
                            [.25, 0.0, 0.035]
                    little:
                        joint0:
                            [3, 0.0, 0.4]
                        joint1:
                            [.6, 0.0, 0.1]
                        joint2:
                            [.25, 0.0, 0.035]
                            
            right_arm:
                joint0:
                    [400.0, 0, 50]
                joint1:
                    [300.0, 0, 40]
                joint2:
                    [100.0, 0, 10]
                joint3:
                    [70.0, 0, 7]
                joint4:
                    [40.0, 0, 2]
                joint5:
                    [10.0, 0, .5]
                joint6:
                    [3.0, 0, .3]
                hand:
                    thumb:
                        joint0:
                            [6, 0.0, 0.3]
                        joint1:
                            [3, 0.0, 0.4]
                        joint2:
                            [.6, 0.0, 0.1]
                        joint3:
                            [.25, 0.0, 0.035]
                    index:
                        joint0:
                            [6, 0.0, 0.3]
                        joint1:
                            [3, 0.0, 0.4]
                        joint2:
                            [.6, 0.0, 0.1]
                        joint3:
                            [.25, 0.0, 0.035]
                    middle:
                        joint0:
                            [6, 0.0, 0.3]
                        joint1:
                            [3, 0.0, 0.4]
                        joint2:
                            [.6, 0.0, 0.1]
                        joint3:
                            [.25, 0.0, 0.035]
                    ring:
                        joint0:
                            [3, 0.0, 0.4]
                        joint1:
                            [.6, 0.0, 0.1]
                        joint2:
                            [.25, 0.0, 0.035]
                    little:
                        joint0:
                            [3, 0.0, 0.4]
                        joint1:
                            [.6, 0.0, 0.1]
                        joint2:
                            [.25, 0.0, 0.035]
                            
    # list of dependencies with a scale to apply to commands (pos, vel, effort)
    # parent:
    #     children: list of dependent joints
    #     factors: list of scale values
    # a joint can be dependent on itself if a scale needs to be applied to commands
    dependency:
        r2:
            left_arm/hand:
                index/joint2:
                    children: /r2/left_arm/hand/index/joint3
                    factors: 1.0
                    
                middle/joint2:
                    children: /r2/left_arm/hand/middle/joint3
                    factors: 1.0
                    
                ring/joint0:
                    children: 
                        - /r2/left_arm/hand/ring/joint0
                        - /r2/left_arm/hand/ring/joint1
                        - /r2/left_arm/hand/ring/joint2
                    factors:
                        - 0.5
                        - 0.5
                        - 0.5
                    
                little/joint0:
                    children: 
                        - /r2/left_arm/hand/little/joint0
                        - /r2/left_arm/hand/little/joint1
                        - /r2/left_arm/hand/little/joint2
                    factors:
                        - 0.5
                        - 0.5
                        - 0.5
                    
            right_arm/hand:
                index/joint2:
                    children: /r2/right_arm/hand/index/joint3
                    factors: 1.0
                    
                middle/joint2:
                    children: /r2/right_arm/hand/middle/joint3
                    factors: 1.0
                    
                ring/joint0:
                    children: 
                        - /r2/right_arm/hand/ring/joint0
                        - /r2/right_arm/hand/ring/joint1
                        - /r2/right_arm/hand/ring/joint2
                    factors:
                        - 0.5
                        - 0.5
                        - 0.5
                    
                little/joint0:
                    children: 
                        - /r2/right_arm/hand/little/joint0
                        - /r2/right_arm/hand/little/joint1
                        - /r2/right_arm/hand/little/joint2
                    factors:
                        - 0.5
                        - 0.5
                        - 0.5
                    
